build_from:
  amd64: ghcr.io/home-assistant/base:latest
  armhf: ghcr.io/home-assistant/armhf-base:latest
  armv7: ghcr.io/home-assistant/armv7-base:latest
  arm64: ghcr.io/home-assistant/aarch64-base:latest

codenotary: notarize

args:
  TEMPIO_VERSION: 2021.4.0
