build_from:
  amd64: docker.io/library/python:3.11-alpine
  aarch64: docker.io/library/python:3.11-alpine
  armv7: docker.io/library/python:3.11-alpine

args:
  BUILD_FROM: docker.io/library/python:3.11-alpine