name: "HA NILM Detector"
description: "Detect appliances from power consumption patterns"
version: "0.1.6"
slug: "ha_nilm_detector"
startup: application
boot: auto
arch:
  - amd64
  - aarch64
  - armv7
init: false
options:
  log_level: info
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)
  home_assistant:
    entity_id_prefix: str
